//
// Generated by afu_json_mgr from ../hw/afu.json
//

#ifndef __AFU_JSON_INFO__
#define __AFU_JSON_INFO__

#define AFU_ACCEL_NAME "afu"
#define AFU_ACCEL_UUID "9F0C38BE-CB5B-45C8-B3D3-B9A3AAEF0CB6"
#define AFU_IMAGE_POWER 0
#define AFU_TOP_IFC "ccip_std_afu"

#endif // __AFU_JSON_INFO__
